log_level = "warn"
outputs = { Targets = ["DP-1", "DP-2"] }
position = "Top"
app_launcher_cmd = "rofi -show drun"

[modules]
left = [ [ "appLauncher", "Updates" ], ["sunbattery", "Tray", "Notification"] ]
center = [ ["Workspaces" ]  ]
right = [ "SystemInfo", [ "Clock", "Privacy", "Settings" ] ]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'kitty -e bash -c "sudo pacman -Syu && yay -Qua; echo Done - Press enter to exit; read" &'

[workspaces]
visiblity_mode = "All"
enable_workspace_filling = false
# workspace_names = ["一","二","三","四","五","六","七","八","九","十",]

[[CustomModule]]
name = "appLauncher"
icon = "󱗼"
command = "rofi -show drun"

[window_title]
mode = "Class"
truncate_title_after_length = 50

[settings]
lock_cmd = "playerctl --all-players pause; nixGL hyprlock &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"

[appearance]
style = "Islands"
# style = "Gradient"
opacity = 0.6

primary_color = "#d79921"
success_color = "#98971a"
text_color = "#ebdbb2"
workspace_colors = [ "#d79921", "#98971a" ]
special_workspace_colors = [ "#d79921", "#98971a" ]

[appearance.menu]
opacity = 0.8
backdrop = 0.2

[appearance.danger_color]
base = "#fb4934"
weak = "#fabd2f"

[appearance.background_color]
base = "#282828"
weak = "#3c3836"
strong = "#928374"

[appearance.secondary_color]
base = "#0c0d14"

[[CustomModule]]
name = "Notification"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[[CustomModule]]
name = "sunbattery"
# icon = " "
command = "$HOME/bin/hacli status sensor.battery_1_soc | jq --unbuffered --compact-output"
listen_cmd = "$HOME/bin/hacli status sensor.battery_1_soc | jq --unbuffered --compact-output"

